In [1]:
import torch

In [2]:
sample = torch.Tensor([[1, 2, 3], [4, 5, 6]])

In [5]:
sample.max(dim=1)

(tensor([3., 6.]), tensor([2, 2]))

In [6]:
from dqn_agent import ReplayBuffer

In [11]:
buffer = ReplayBuffer(action_size=4, buffer_size=10, batch_size=2, seed=0)

In [12]:
buffer.add(state=[1, 2, 3], action=0, reward=1, next_state=[4, 5, 6], done=False)
buffer.add(state=[4, 5, 6], action=1, reward=0, next_state=[7, 8, 9], done=False)
buffer.add(state=[7, 8, 9], action=2, reward=1, next_state=[10, 11, 12], done=False)
buffer.add(state=[10, 11, 12], action=3, reward=0, next_state=[13, 14, 15], done=False)
buffer.add(state=[13, 14, 15], action=0, reward=1, next_state=[13, 14, 15], done=True)

In [21]:
samples = buffer.sample()

In [22]:
states, actions, rewards, next_states, dones = samples

In [23]:
dones

tensor([[1.],
        [0.]])

In [34]:
dones_reversed = 1 - dones
dones_reversed

tensor([[0.],
        [1.]])

In [26]:
rewards

tensor([[1.],
        [0.]])

In [30]:
torch.Tensor([1, 2]) * torch.Tensor([3, 4])

tensor([3., 8.])

In [31]:
gamma = 0.995
max_next_action_values = torch.Tensor([[1.0], [2.0]])
y = rewards + gamma * max_next_action_values * dones_reversed

In [32]:
y

tensor([[1.0000],
        [1.9900]])

In [39]:
gather = torch.Tensor([[1, 3, 2], [5, 6, 4]]).gather(dim=1, index=torch.LongTensor([[1], [0]], ))
gather

tensor([[3.],
        [5.]])